---
- name: redhat | Enabling EPEL repo
  ansible.builtin.yum:
    name: ["epel-release"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_facts['distribution'] != "Fedora"

- name: redhat | Installing Pre-Reqs
  ansible.builtin.yum:
    name: ["lldpd"]
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - config_install_lldp | bool
    - ansible_facts['distribution'] != "Fedora"

- name: redhat | Installing bridge-utils
  ansible.builtin.yum:
    name: ["bridge-utils"]
  become: true
  register: result
  until: result is successful
  when: >
    config_network_bridges and
    ansible_facts['distribution'] != "Fedora"

- name: redhat | Installing VLAN Packages
  ansible.builtin.yum:
    name: ["vconfig"]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    config_network_vlans and
    ansible_facts['distribution'] != "Fedora"

- name: redhat | Enabling Bonding
  community.general.modprobe:
    name: bonding
    state: present
  become: true
  when: config_network_bonds

- name: redhat | Enabling Bridging
  community.general.modprobe:
    name: bridge
    state: present
  become: true
  when: config_network_bridges

- name: redhat | Configuring Interfaces
  ansible.builtin.template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item['name'] }}"
    owner: root
    group: root
    mode: 0644
  register: config_interface
  become: true
  with_items: "{{ network_interfaces }}"
  when: >
    config_network_interfaces and
    item['configure']

- name: redhat | Configuring Bonds
  ansible.builtin.template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item['name'] }}"
    owner: root
    group: root
    mode: 0644
  register: config_bond
  become: true
  with_items: "{{ network_bonds }}"
  when: >
    config_network_bonds and
    item['configure']

- name: redhat | Configuring Bridges
  ansible.builtin.template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item['name'] }}"
    owner: root
    group: root
    mode: 0644
  register: config_bridge
  become: true
  with_items: "{{ network_bridges }}"
  when: >
    config_network_bridges and
    item['configure']

- name: redhat | Restarting Network Bonds
  ansible.builtin.shell: bash -c "ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  with_items: "{{ config_bond['results'] }}"
  when: >
    config_network_bonds and
    enable_configured_interfaces_after_defining and
    item['item']['configure'] and
    item['changed']

- name: redhat | Restarting Network Bridges
  ansible.builtin.shell: bash -c "ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  with_items: "{{ config_bridge['results'] }}"
  when: >
    config_network_bridges and
    enable_configured_interfaces_after_defining and
    item['item']['configure'] and
    item['changed']

- name: redhat | Restarting Network Interfaces
  ansible.builtin.shell: bash -c "ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  with_items: "{{ config_interface['results'] }}"
  when: >
    config_network_interfaces and
    enable_configured_interfaces_after_defining and
    item['item']['configure'] and
    item['changed']
