---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bullseye
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
  - name: bionic
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
  - name: jammy
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
  - name: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: true
  - name: rockylinux8
    image: geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
