---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bullseye
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
  - name: bionic
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    pre_build_image: true
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
  - name: jammy
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    # Required to update APT cache in Jammy
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
